M48
; DRILL file KiCad 10.0.5 date 2026-09-26T15:00:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T15:00:44-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X31.11Y-5.605
X36.89Y-5.605
T2
X5.0Y-5.0
X5.0Y-155.0
X195.0Y-5.0
X195.0Y-155.0
M30
